/* ============================================================
   VALIDATION + EXPORT (JSON, .inc)
   copperbands.inc is consumed by test_asm_copper_tool.s via #include
   ============================================================ */

// Generic download helper. Chrome/Edge can reject blob: navigation when the
// page is opened as file://, so a data: URL is used in that case.
function downloadBytes(filename, bytes, mimeType='application/octet-stream'){
  const a = document.createElement('a');
  a.download = filename;
  let revoke = null;
  if (window.location.protocol === 'file:'){
    let bin = '';
    bytes.forEach(v => { bin += String.fromCharCode(v); });
    a.href = 'data:' + mimeType + ';base64,' + btoa(bin);
  } else {
    revoke = URL.createObjectURL(new Blob([bytes], {type:mimeType}));
    a.href = revoke;
  }
  document.body.appendChild(a);
  a.click();
  a.remove();
  if (revoke) setTimeout(()=>URL.revokeObjectURL(revoke), 1000);
}

function downloadTextFile(filename, text, mimeType='text/plain;charset=utf-8'){
  downloadBytes(filename, new TextEncoder().encode(text), mimeType);
}

// Shared by export and JSON import. `bands` in the order to be checked
// (hint bands must be strictly increasing in that order).
function validateBands(bands, heightTiles){
  const errors = [];
  const vbands = bands.filter(b=>b.loadMode==='vblank');
  const hbands = bands.filter(b=>b.loadMode==='hint');

  if (vbands.length !== 1) errors.push('There must be exactly one vblank band.');
  else if (vbands[0].startTileRow !== 0) errors.push('The vblank band must start at tile-row 0.');
  if (vbands.length + hbands.length !== bands.length) errors.push('Every band needs loadMode "vblank" or "hint".');
  if (!hbands.length) errors.push('At least one hint band is required.');

  const ids = new Set();
  for (const b of bands){
    if (ids.has(b.id)) errors.push(`Duplicate band id "${b.id}".`);
    ids.add(b.id);
    if (!Array.isArray(b.colors) || b.colors.length !== 16){
      errors.push(`Band ${b.id}: colors must be an array of 16 values.`);
      continue;
    }
    b.colors.forEach((c,i)=>{
      if (!Number.isInteger(c) || c < 0 || c > 0x0EEE || !isValidColor(c))
        errors.push(`Band ${b.id}, color ${i}: not a valid 0x0EEE color.`);
    });
  }

  let prev = null;
  for (const b of hbands){
    const r = b.startTileRow;
    if (!Number.isInteger(r) || r < 1 || r > heightTiles-1){
      errors.push(`Band ${b.id}: startTileRow must be an integer from 1 to ${heightTiles-1}.`);
      continue;
    }
    if (prev !== null){
      if (r <= prev) errors.push(`Band ${b.id}: startTileRow must be strictly increasing (no duplicates).`);
      else if (r - prev < MIN_BAND_SPACING_ROWS)
        errors.push(`Band ${b.id}: must be at least ${MIN_BAND_SPACING_ROWS} tile-rows after the previous band.`);
    }
    prev = r;
  }
  return errors;
}

function validateState(){
  return validateBands(sortedBands(), state.imageHeightTiles);
}

document.getElementById('btnExportJson').onclick = ()=>{
  const errors = validateState();
  if (errors.length){ alert('Cannot export JSON:\n'+errors.join('\n')); return; }
  const out = {
    imageHeightTiles: state.imageHeightTiles,
    sourceImage: state.sourceImage || "untitled.png",
    imageOffsetTiles: imgOffset(),
    bands: sortedBands().map(b=>({
      id: b.id, startTileRow: b.startTileRow, loadMode: b.loadMode, colors: b.colors
    }))
  };
  downloadTextFile('bands.json', JSON.stringify(out,null,2), 'application/json;charset=utf-8');
};

/* copperbands.inc: plain GAS data, pulled in by the test with
       #include "copperbands.inc"
   (the preprocessor looks next to the .s first, so no paths are needed).
   CopperBandsData : vblank band + hint bands, 16 words (32 bytes) each
   BandTableStart  : word initial_gap, then per hint band
                     { word gap_after_band, long band_offset_in_CopperBandsData } */
function buildInc(){
  const bands = sortedBands();
  const hint = bands.slice(1);
  const w = c => '0x' + c.toString(16).toUpperCase().padStart(4,'0');

  let s = '/* Generated by CopperBarTool. Do not edit. */\n\nCopperBandsData:\n';
  bands.forEach((b,i)=>{
    s += `    /* ${i === 0 ? 'vblank' : 'row ' + b.startTileRow} (offset ${i*32}) */\n`;
    s += `    .word ${b.colors.slice(0,8).map(w).join(', ')}\n`;
    s += `    .word ${b.colors.slice(8).map(w).join(', ')}\n`;
  });

  s += '\nBandTableStart:\n';
  s += `    .word ${hint[0].startTileRow*TILE_H - HINT_SETUP_LATENCY}    /* initial idle gap */\n`;
  hint.forEach((b,i)=>{
    const start = b.startTileRow*TILE_H;
    const gap = (i+1 < hint.length)
      ? hint[i+1].startTileRow*TILE_H - start - BAND_STRIDE_OVERHEAD
      : LAST_BAND_GAP;
    s += `    .word ${gap}    /* gap after band at row ${b.startTileRow} */\n`;
    s += `    .long ${32*(i+1)}\n`;
  });
  s += `    .word 0x7FFF    /* sentinel, not a real gap */\n`;
  s += `    .long 0         /* sentinel, offset never used */\n`;
  s += 'BandTableEnd:\n';
  return s;
}

const outInfo = document.getElementById('outInfo');
const FS_OK = 'showDirectoryPicker' in window;
let outDir = null;

function idbOpen(){
  return new Promise((res,rej)=>{
    const r = indexedDB.open('copperbar-tool', 1);
    r.onupgradeneeded = ()=>r.result.createObjectStore('kv');
    r.onsuccess = ()=>res(r.result);
    r.onerror = ()=>rej(r.error);
  });
}
async function idbGet(key){
  const db = await idbOpen();
  return new Promise((res,rej)=>{
    const q = db.transaction('kv').objectStore('kv').get(key);
    q.onsuccess = ()=>res(q.result);
    q.onerror = ()=>rej(q.error);
  });
}
async function idbSet(key, val){
  const db = await idbOpen();
  return new Promise((res,rej)=>{
    const tx = db.transaction('kv','readwrite');
    tx.objectStore('kv').put(val, key);
    tx.oncomplete = ()=>res();
    tx.onerror = ()=>rej(tx.error);
  });
}

async function chooseOutDir(){
  try {
    outDir = await window.showDirectoryPicker({ id:'copperbar-out', mode:'readwrite' });
    try { await idbSet('outDir', outDir); } catch(e){}
    outInfo.textContent = `out: ${outDir.name}`;
  } catch(e){
    if (e.name !== 'AbortError') alert('Cannot open folder: ' + e.message);
  }
}

async function ensureWritable(dir){
  const opts = { mode:'readwrite' };
  if (await dir.queryPermission(opts) === 'granted') return true;
  return (await dir.requestPermission(opts)) === 'granted'; // needs a user gesture (the click)
}

async function writeFileTo(dir, name, bytes){
  const fh = await dir.getFileHandle(name, { create:true });
  const w = await fh.createWritable();
  await w.write(bytes);
  await w.close();
}

(async function initOutDir(){
  const btn = document.getElementById('btnOutDir');
  if (!FS_OK){
    btn.style.display = 'none';
    outInfo.textContent = 'out: downloads (no folder access in this browser)';
    return;
  }
  btn.onclick = chooseOutDir;
  try { outDir = (await idbGet('outDir')) || null; } catch(e){ outDir = null; }
  outInfo.textContent = outDir ? `out: ${outDir.name}` : 'out: not set';
})();

document.getElementById('btnExportInc').onclick = async ()=>{
  const errors = validateState();
  if (errors.length){ alert('Cannot export .inc:\n'+errors.join('\n')); return; }
  const text = buildInc();

  if (FS_OK && !outDir) await chooseOutDir();   // first export: ask for the folder (cancel = download)
  if (outDir){
    try {
      if (!(await ensureWritable(outDir))) throw new Error('permission denied');
      await writeFileTo(outDir, 'copperbands.inc', new TextEncoder().encode(text));
      outInfo.textContent = `out: ${outDir.name} \u00b7 saved ${new Date().toLocaleTimeString()}`;
      return;
    } catch(e){
      alert(`Could not write to "${outDir.name}" (${e.message}). Falling back to download.`);
    }
  }
  downloadTextFile('copperbands.inc', text);
};