/* ------------------------------------------------------------------
   Copper bands test - SGDK, GNU AS, M68000

   Persistent registers (main + handlers):
     %a1 = VDP data port (0xC00000)
     %a0 = color read pointer of the ACTIVE band
     %d2 = longword to write on the current active line
     %d1 = line counter (active or idle), for DBRA
     %a3 = table read pointer (next entry to prefetch)
     %d3 = prefetch: idle gap AFTER the pending band
     %a4 = prefetch: pointer to the pending band's colors
     %a5 = fixed base of the CopperBandsData blob
   Scratch:
     %d0 = main only (VDP status, counters) - handlers must NOT touch it
     %d4 = handlers only (prefetch)
     %a2 = main only (VBlank reload)

   Data: generated by CopperBarTool into copperbands.inc (this .s never changes)
     CopperBandsData : vblank band + hint bands, 16 words each
     BandTableStart  : word  initial_gap            ; idle before the 1st hint band, DBRA value (lines-1)
                       N x { word gap_after_band    ; idle AFTER that band, DBRA value (lines-1)
                             long band_offset }     ; offset from CopperBandsData
   Exporter rules:
        - every gap (initial and "after band") must be >= 1 as a DBRA value
          (>= 2 idle lines), since the first idle line after a band does the prefetch
        - the gap after the last band must cover the rest of the frame (e.g. 0x7FFF)
        - at least 1 hint band
   ------------------------------------------------------------------ */

.section .text.asmtest

.globl  main
.globl  HIntActive
.globl  HIntIdle
.globl  HIntIdlePrefetch

.extern SYS_setHIntCallback
.extern hintCaller

/* Loads the vblank band and prepares everything for the frame. VBlank only. */
.macro CopperFrameInit
        move.l  #0xC0000000,0xC00004.l         /* CRAM write, address 0 */
        lea     CopperBandsData.l,%a2
        moveq   #7,%d0
1:      move.l  (%a2)+,(%a1)
        dbra    %d0,1b

        lea     BandTableStart.l,%a3
        move.w  (%a3)+,%d1                     /* initial idle gap */
        move.w  (%a3)+,%d3                     /* prefetch of the 1st hint band */
        move.l  (%a3)+,%d0
        lea     0(%a5,%d0.l),%a4
        move.l  #HIntIdle,hintCaller+2
.endm

main:
        move.l  #HIntIdle,-(%sp)
        jsr     SYS_setHIntCallback
        addq.l  #4,%sp

        move.w  #0x8F02,0xC00004.l             /* auto-increment 2 */
        lea     0xC00000.l,%a1
        lea     CopperBandsData.l,%a5

        /* Tile 0: 4x4 grid of 2x2 meta-pixels, one per palette index 0..15.
           Every nametable entry is 0 (SGDK clears the planes), so this one
           tile fills the whole screen. Written before H-INT is enabled. */
        move.l  #0x40000000,0xC00004.l         /* VRAM write, address 0 */
        move.w  #0x0011,(%a1)
        move.w  #0x2233,(%a1)
        move.w  #0x0011,(%a1)
        move.w  #0x2233,(%a1)
        move.w  #0x4455,(%a1)
        move.w  #0x6677,(%a1)
        move.w  #0x4455,(%a1)
        move.w  #0x6677,(%a1)
        move.w  #0x8899,(%a1)
        move.w  #0xAABB,(%a1)
        move.w  #0x8899,(%a1)
        move.w  #0xAABB,(%a1)
        move.w  #0xCCDD,(%a1)
        move.w  #0xEEFF,(%a1)
        move.w  #0xCCDD,(%a1)
        move.w  #0xEEFF,(%a1)

        CopperFrameInit

        move.w  #0x8A00,0xC00004.l             /* H-INT every scanline */
        move.w  #0x8014,0xC00004.l             /* H-INT on */

.mainloop:
.wait_vblank_start:
        move.w  0xC00004.l,%d0
        btst    #3,%d0
        beq.s   .wait_vblank_start

        CopperFrameInit                         /* inside VBlank */

.wait_vblank_end:
        move.w  0xC00004.l,%d0
        btst    #3,%d0
        bne.s   .wait_vblank_end

        bra.s   .mainloop


.section .ramprog
.even

/* Active line. "Continue" path = 2 moves + dbra + rte; "last" path switches handler. */
HIntActive:
        move.l  %d2,(%a1)
        dbra    %d1,.active_continue

        move.l  #HIntIdlePrefetch,hintCaller+2
        move.l  %d3,%d1
        rte

.active_continue:
        move.l  (%a0)+,%d2
        rte


/* Normal idle: dbra + rte. On the "last" line the next band is activated. */
HIntIdle:
        dbra    %d1,.idle_done

        move.l  #0xC0000000,0xC00004.l
        move.l  %a4,%a0
        move.l  (%a0)+,%d2
        moveq   #7,%d1
        move.l  #HIntActive,hintCaller+2
.idle_done:
        rte


/* One-shot: first idle line after a band. Consumes the line, prefetches the
   next table entry (if any) and restores HIntIdle. Requires DBRA gap >= 1. */
HIntIdlePrefetch:
        move.l  #HIntIdle,hintCaller+2
        subq.w  #1,%d1

        move.w  (%a3)+,%d3
        move.l  (%a3)+,%d4
        lea     0(%a5,%d4.l),%a4
        rte


.section .rodata
.even

#include "copperbands.inc"